### ISSUE TITLE
Flying workers cannot place resources in flying container

### ISSUE THREAD

**Issue by KeithSammut** [ZetaGlest/zetaglest-source#100]
While I was playing with the specialists faction, I noticed that the flying workers which were loaded with resources, were not transfering their resources once they touched the air container, they just moved towards it and stopped, surrounding it.

![image](https://user-images.githubusercontent.com/19623478/37961802-8af4e28c-31b9-11e8-957b-2b8730d67275.png)

It would be better, if flying units with a resources stored ability, could store resources as the land units

**Comment by andy5995** [comment]
That's done with @Ishmaru's Assault Command mod. The helicopters can harvest. But the "storage unit" is land-based.

**Comment by mathusummut** [comment]
That's the problem, that air-based storage containers are not recognized by the engine.

**Comment by Jammyjamjamman** [comment]
Any unit can now deposit resources to land or flying units.

**Comment by KeithSammut** [comment]
Awesome
