### ISSUE TITLE
Game is too dark.

### ISSUE THREAD

**Issue by Jammyjamjamman** [ZetaGlest/zetaglest-source#107]
I hear a lot of complaints about MG being too dark in-game, and I find this a problem too.
One of my solutions is to set DayTime (in `glest.ini`) to a really big number, so that it's day all the time. It would be nicer however, if:

* there was an option to switch off day
* the game was just made brighter

I wouldn't mind losing night time, because it does not affect the actual game (although I guess it does somewhat add realism).

**Comment by mathusummut** [comment]
Maybe what we should do is modify the tilesets to make night less dark.

**Comment by biels** [comment]
This made me remember that very long ago when I was really into Glest and then Megaglest I had to pull down the blind and switch of any other light to be able to play the game. I wonder how many people will have done the same 🤣

**Comment by KeithSammut** [comment]
I very m,uch agree with you biel, it's a hassel arranging the screen brightness everytime you play the game, especially when it's night time in the game.

**Comment by mathusummut** [comment]
@KeithSammut has fixed this, if any issues are encountered, please comment now or it will be closed.
