### ISSUE TITLE
paths in glest.ini should be more flexible

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#113]
as discussed here: https://github.com/ZetaGlest/zetaglest-source/pull/111#issuecomment-386437394

(But add any comments to this ticket)

Specifically, these paths:

https://github.com/ZetaGlest/zetaglest-source/blob/3022427fd71aef3f2a8c68a8902ef3111367eaa7/mk/linux/glest.ini#L98-L113

**Comment by andy5995** [comment]
I think for the sake of simplicity, those sounds should just be hard-coded into coredata.cpp again.

**Comment by mathusummut** [comment]
No, please don't!!!!! In /mk/windows there are two glest.ini, they both have different paths, one for development and one for release.

**Comment by mathusummut** [comment]
I understood incorrectly, I thought the paths would be hardcoded 😅

**Comment by andy5995** [comment]
I just mean specifying the paths + filenames within the source code, as it was before. That way it will always match CUSTOM_DATA_INSTALL_PATH or which path all other data goes into.

**Comment by mathusummut** [comment]
Oh, then no, we **cannot** do that, I had understood you correctly the first time.

**Comment by andy5995** [comment]
The problem is that the installer is looking at the relative paths, so if zetaglest is run from a different directory, it just throws an error when trying to find these files.

>Oh, then no, we cannot do that, I had understood you correctly the first time.

They were hard-coded before.

```
; sfx
; These can be over-ridden by adding the variables to your glestuser.ini
; file.
;
; FIXME: There should be a way to use the "DataPath" variable
; here (defined above)
PlaySoundAttention=../../../zetaglest-data/data/core/menu/sound/attention.wav
PlaySoundHighlight=../../../zetaglest-data/data/core/menu/sound/highlight.wav
PlaySoundNewServer=../../../zetaglest-data/data/core/menu/sound/attention.wav
PlaySoundMarker=../../../zetaglest-data/data/core/menu/sound/sonar.wav

; it's recommended that users not over-ride these. The sounds are just for
; menu clicks and should remain very short in duration.
PlaySoundMenuClickA=../../../zetaglest-data/data/core/menu/sound/click_a.wav
PlaySoundMenuClickB=../../../zetaglest-data/data/core/menu/sound/click_b.wav
PlaySoundMenuClickC=../../../zetaglest-data/data/core/menu/sound/click_c.wav
```
