### ISSUE TITLE
Redo AI enhancement + reduce max multiplier to 3.5

### ISSUE THREAD

**Issue by mathusummut** [ZetaGlest/zetaglest-source#122]
I suggest undoing this reversion:
https://github.com/ZetaGlest/zetaglest-source/commit/e018b260569a95769f143d2e3cf8142f0ee1250e

And compensating by reducing the max AI multiplier from 4.9 to 3.5.

**Comment by andy5995** [comment]
I'm okay with that, as long as @Jammyjamjamman agrees.

This patch file can be used:

https://patch-diff.githubusercontent.com/raw/ZetaGlest/zetaglest-source/pull/118.patch

using the *reverse* option of the patch command.

https://www.poftut.com/patch-command-tutorial-with-examples-for-linux/

**Comment by mathusummut** [comment]
@Jammyjamjamman do you agree?

**Comment by Jammyjamjamman** [comment]
Yes, I think this is a good idea. Also, I don't think this will make much difference for the old AI (if we don't use my hack).

**Comment by andy5995** [comment]
Completed by @mathusummut in https://github.com/ZetaGlest/zetaglest-source/commit/91d8fea8074e33fc70c26caa49769bf089ab6c5d
