### ISSUE TITLE
change how observer mode works

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#13]
Right now, observers use a player slot.

For example, if you have a 3 v 3 game on six player map, there is not 7th slot for an observer unless the map is changed to a 7 or 8 player map.

On a 8 player map with 8 people playing, there would be no room for an observer.

There should be a way for observers to join without using a player slot.

**Comment by andy5995** [comment]
I can't believe I really did this! Or at least.. that I was able to do it so quickly. I've been picking at it for a few days.

You can see in the screenshot below that I need to move some text on the setup menu around, but basically as far as testing, I was able to:

* start a server
* checkbox -> allow observers
* connect with a 2nd client ; select slot 5 on a 4 player map and choose "observer" for faction
* start the server and neither server nor client crashed!
* game started and 2nd client was in observer mode, as intended. I quit after  a minute. All seems ok initially.

![screenshot_2018-01-22_02-30-47](https://user-images.githubusercontent.com/16764864/35211612-d5b96830-ff1c-11e7-866d-ce98ab7dfce2.png)

There wasn't much code I had to add or change (though I took the opportunity to update the license header at the top of the source files I edited).

To see the changes, take a look at https://github.com/ZetaGlest/zetaglest-source/pull/14/files

I want to clean up my code changes better though, before I merge in the changes.

**Comment by Jammyjamjamman** [comment]
not sure yet how to fix it, but this is the current problem:
![screen4](https://user-images.githubusercontent.com/6165871/35362686-45a93c18-015e-11e8-8031-2c7e45bf6a11.jpg)
Everything could be shifted down, but this would make the comment box even smaller, which is unideal.
An ideal solution is a scroll for player positions, I'll have a look to see if that's possible.

**Comment by andy5995** [comment]
I'll make a note on the ticket for others...

There's scrollbar code being used in https://github.com/ZetaGlest/zetaglest-source/blob/464860aa023e4089f4c6f108e019d66d60052581/source/glest_game/menu/menu_state_masterserver.cpp#L75

**Comment by andy5995** [comment]
Unfortunately I didn't get this patch done in only 1 commit.

For reference, here were the first 2 parts:

42541caab7d457d0c73f63ec6dc1e8816ceff704
31d91e854416384f07b512aed1ffd8ef3cdbb4ca

**Comment by andy5995** [comment]
Most recent commit that adds to this patch:

af3ff60cb6c201ad4eed69af748c758a21e1fb07
