### ISSUE TITLE
using only 1 glest.ini file

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#137]
There's 3 glest.ini files, one for Windows, one for Mac, and one for Linux.

How about we move that into one, and put it in https://github.com/ZetaGlest/zetaglest-source/tree/develop/mk/shared

afaik, the only difference in the 3 files are the direction in which the slashes lean.

Shouldn't be too difficult to make a patch that would convert those slashes at run time.

**Comment by mathusummut** [comment]
No, the Windows has 2 glest.ini, one for development and one for release.
