### ISSUE TITLE
if a worker is in a selection group with units that can attack, attack mode becomes disabled

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#156]
If a worker is in a selection group with units that can attack, attack mode becomes disabled.

right clicking will still initiate an attack, but the "a" key won't work and the attack icon on the right is disabled.
![screen99](https://user-images.githubusercontent.com/16764864/41503882-400829b6-71a4-11e8-99f8-c5124e128e2e.jpg)

Mentioned by @biels in #8

**Comment by mathusummut** [comment]
(This is now solved.)[https://github.com/ZetaGlest/zetaglest-source/commit/b4b13ec918982c402b5a11c1b13929e0dcd14f64]

**Comment by andy5995** [comment]
@mathusummut You can close stuff automatically and the commit number will also be included

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by andy5995** [comment]
And thanks for doing this!!
