### ISSUE TITLE
Keyboard / hotkeys not working sometimes 

### ISSUE THREAD

**Issue by biels** [ZetaGlest/zetaglest-source#160]
Me and my friends (we are all on windows) faced a bug where the game would not respond to keyboard events. It could be related with the first start of the game after installing, but I am not sure of that.

**Comment by andy5995** [comment]
@mathusummut do you have any problems on Windows with the current code?

**Comment by mathusummut** [comment]
I never experienced this bug, for me the keyboard always works fine.

**Comment by andy5995** [comment]
@biels can you tell us if you or your friends are experiencing this with the current source code?

**Comment by biels** [comment]
My friend had issues with the keyboard on windows several times. The
keyboard would not work. I hadn't had the time to read the thread but
throwing it out here just in case it helps.

**Comment by andy5995** [comment]
Ok.. so no recent reports, and no details that would help with debugging.

I'll close the ticket. Please let us know if this happens again. At a minimum, we'd need to know the Windows version numbers of affected players.
