### ISSUE TITLE
Double click on the floor to move (click to attack)

### ISSUE THREAD

**Issue by biels** [ZetaGlest/zetaglest-source#162]
Many players are having issues with the attack / move mechanics. Originally the problem was that the default command was "Move" and units would pass in front of enemy units without attacking them. Then in ZetaGlest we switched it up to "Attack". Now players are getting confused when they want to retreat and start telling units top move back yet no unit seems to take a hint. 
My solution would be to assign the command "Move" to the double click on the floor. That way you can easily switch between the attack and move modes without touching the keyboard. The "M" key approach works but is far from ideal

**Comment by mathusummut** [comment]
It already is like that! Double right-clicking sends a move command :)
