### ISSUE TITLE
icons larger than clickable area

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#165]
me and @Jammyjamjamman  noticed this yesterday, related to #75 

The icons extend "outside" the clickable area.

You see in this screenshot, the mouse is on the obelisk icon, and everything is ok:

![screen100](https://user-images.githubusercontent.com/16764864/41736965-945367e4-7553-11e8-9c33-ed718d9a231f.jpg)

But if I move the mouse just a little bit more to the right, the tooltip for the creation of the obelisk goes away, and if I click, the menu just disappears and nothing happens.

![screen101](https://user-images.githubusercontent.com/16764864/41736966-9466d130-7553-11e8-8b3b-35ffe56f5b84.jpg)

**Comment by mathusummut** [comment]
[This is now fixed.](https://github.com/ZetaGlest/zetaglest-source/commit/656816084c4e59394ed1d1c1ebdf9309fb2d8b67)
