### ISSUE TITLE
Implement double right-click to move

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#167]
A desired feature is to implement double right-click to move units instead of attacking. We tried to implement this feature, but unfortunately it was found to be inconsistent, and not work well during network games.

**Comment by andy5995** [comment]
I couldn't either, but it's happened to me a couple times and to @biels so let's keep this ticket open for now.

**Comment by biels** [comment]
Is it possible that the feature exists on the latest develop but when playing we're using the "release" version and we still don't have it?

**Comment by andy5995** [comment]
That's right.

**Comment by biels** [comment]
It is working on the latest version that I finally got to compile.

**Comment by biels** [comment]
However I think the binding should be either configurable or hardcoded but switched up in that 1 click -> move, 2 clicks -> attack. Should i open a separate issue?

**Comment by andy5995** [comment]
Playing with @Jammyjamjamman earlier tonight, I had this problem several times. Still not sure how to reproduce it every time.

>However I think the binding should be either configurable or hardcoded but switched up in that 1 click -> move, 2 clicks -> attack. Should i open a separate issue?

Yes, @biels . I think having it configurable would be a good option.

**Comment by mathusummut** [comment]
Is this still an issue, please?

**Comment by andy5995** [comment]
I forget about it. I'll tell @alketii and remember to try it some more.

**Comment by mathusummut** [comment]
Double right-clicking was disabled due to inconsistencies.

**Comment by mathusummut** [comment]
This was voted to be user-unfriendly.

**Comment by linux-player9** [comment]
The double click to move was a good feature since unit attack by default
