### ISSUE TITLE
Unit's no longer fade away when they die (introduced in c15488a )

### ISSUE THREAD

**Issue by Jammyjamjamman** [ZetaGlest/zetaglest-source#169]
The new transparency seems to break how the old transparency works. The archmage and flying carpet no longer fade away when they die (some amazingly edited screenies ;D ):
![screen47](https://user-images.githubusercontent.com/6165871/41813781-3fcc3402-7734-11e8-8bb2-94e6e36a2286.jpg)
![screen43](https://user-images.githubusercontent.com/6165871/41813789-7f0173a8-7734-11e8-8e32-51b53f937891.jpg)

The bug first appears at commit c15488a

**Comment by mathusummut** [comment]
I'm on it

**Comment by mathusummut** [comment]
[This is now fixed.](https://github.com/ZetaGlest/zetaglest-source/commit/d142d80b05710acb487f149dfb6f0d18c748bb5d)
