### ISSUE TITLE
Build fails on Arch Linux

### ISSUE THREAD

**Issue by dafky2000** [ZetaGlest/zetaglest-source#17]
https://pastebin.com/X6g4pT7Y

**Comment by andy5995** [comment]
I see this:

```
$ ack -Q std::reverse
shared_lib/sources/graphics/font.cpp
461:							std::reverse(nonASCIIWordList.begin(),nonASCIIWordList.end());
476:						std::reverse(nonASCIIWordList.begin(),nonASCIIWordList.end());

shared_lib/include/platform/common/byte_order.h
31:    std::reverse(&raw, &raw + sizeof(T));
```

When I look inside those 2 files, the necessary file algorithm is #included in both of them, but there are conditions on them.

**Comment by dafky2000** [comment]
After installing a bunch of dependencies I got a *successful build* although the tests were failing to start after the build.

https://pastebin.com/1MZ3vPvC

The Arch packages I have installed (just a guess on most of them, if I couldn't immediately find one and the lib32 was available I opted for that just in case):

`pacman -S wxgtk3 libcurl-gnutls lib32-sdl2 lib32-openal lua52 cppunit ftgl glew libogg libvorbis miniupnpc libircclient vlc libxml2 libx11 mesa librtmp0 lib32-krb5 libldap libidn2 libpsl libnghttp2 libssh2 xorg-server-xvfb`

**Comment by andy5995** [comment]
>Arch doesn't have developmental packages.  All headers etc are packaged together.

https://bbs.archlinux.org/viewtopic.php?id=47319

That post is 10 years old, so for sdl at least, `pacman -S sdl2` I'd think should be enough.

Hmm.. but there are still "lib..." packages in Arch, obviously. Wonder why there would be discrepancies.

**Comment by dafky2000** [comment]
Here's the updated dependencies from MegaGlest on the Arch package repo

https://www.archlinux.org/packages/community/x86_64/megaglest/

`pacman -S curl ftgl glew glu icu libgl libircclient libvorbis libx11 lua51 miniupnpc openal sdl2 wxgtk3 xerces-c cmake ftjam git mesa`
