### ISSUE TITLE
use "shift" to deselect units

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#172]
How do you de-select a single unit in a selection group?

For example, if I have 4 barracks selected, and I shift-click on one, shouldn't it be de-selected?

Same problem with workers and other mobile units.

**Comment by JoaoMarcosCSilva** [comment]
I believe you can de-select units by ctrl-clicking them.

**Comment by andy5995** [comment]
Oh, good enough!

Does anyone think "shift" should be used for that though?

**Comment by JoaoMarcosCSilva** [comment]
Shift would indeed be better, since using ctrl is pretty counter-intuitive in my opinion. However, changing to shift could create bugs, for example when you try to de-select in an area where there are both selected and not selected units. Do you have any idea how to solve that?
