### ISSUE TITLE
figure out how to give other people access to Travis

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#176]
@mathusummut @Jammyjamjamman and @sexybiggetje could be three people with access to travis, with the ability to restart jobs.

How to give other people besides myself access?

**Comment by mathusummut** [comment]
Apparently it is tied to the GitHub account. I signed in with the correct account (which has admin access), and I am able to restart jobs as necessary. :)

**Comment by andy5995** [comment]
Sounds right. You and @Jammyjamjamman have admin access, @sexybiggetje has write access, which should be all fine for now.
