### ISSUE TITLE
Clients freeze momentarily when server terminates

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#187]
This happens when someone is hosting a network game (not through a headless server)

In a network game, if the host terminates the server before clients disconnect, the clients freeze for several seconds.

This can also happen at the game set-up menu.

I'm not sure how possible it is to prevent the freeze. It's happening because clients are trying to communicate with the server. The freeze ends when the connection times out.

But it would be so much from a UX perspective if the server sent a message to all clients that it's shutting down, so some text could be printed in the chat console.

A message similar to:
"Server is shutting down. Please wait a few moments..."

**Comment by andy5995** [comment]
This was done by by @mathusummut , it just needs more testing before we close the ticket.

**Comment by Jammyjamjamman** [comment]
I don't think the fix worked for me on linux. Didn't notice much difference. :/

**Comment by andy5995** [comment]
cc @ZetaGlest/cpp
