### ISSUE TITLE
Wrong info displayed when ZG detects firewall improperly configured

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#188]
If ZetaGlest detects that a user's firewall won't permit connections, this message is displayed.

![image](https://user-images.githubusercontent.com/16764864/42590284-ff862cf8-8508-11e8-95cf-c5d0f304aa5c.png)

This ticket is dependent on https://github.com/ZetaGlest/zetaglest.github.io/issues/61

**Comment by andy5995** [comment]
The "wrong info" I mentioned is the address showing.. faq.megaglest.org

**Comment by mathusummut** [comment]
[The English variant of "WrongRouterSetup" is fixed](https://github.com/ZetaGlest/zetaglest-data/commit/eb806ae3617291b34df2c2bfd379db754f8b773d). It should be fixed for all languages eventually.

**Comment by andy5995** [comment]
Thanks @mathusummut . I was thinking that it might be easier to maintain in the long-term if we did just have a link listed there. We might consider removing the translations completely and people would just use services that translate web sites. I assume that a lot of non-English speaking people are often in the position of having to translate web sites? @sexybiggetje ? opinions anyone?
