### ISSUE TITLE
units with a sight value of 0 can still see

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#195]
units with a sight value of 0 can still see

https://github.com/ZetaGlest/zetaglest-data/blob/f511135c62de98713b339c06e4cd6f6eaa4dc5ec/techs/zetapack/factions/tech/units/livestock/livestock.xml#L17

**Comment by mathusummut** [comment]
[This bug is now fixed.](https://github.com/ZetaGlest/zetaglest-source/commit/d4f6978105eb0e87b5a959491497e0449c29245b)
