### ISSUE TITLE
reduce the decay time of corpses

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#198]
Would reducing the decay time of corpses help with #142?

**Comment by mathusummut** [comment]
I was thinking we make corpses fade out over time. Would look cool :)

**Comment by andy5995** [comment]
yeah, it would. :)

Perhaps we could compromise: The rate of fade-out changes based on the units currently fading away.

Also would be good to have an option to disable the vanishing corpses. someone suggested that on the MG forum.

**Comment by mathusummut** [comment]
[Happy medium](https://github.com/ZetaGlest/zetaglest-source/commit/55f7bf5f000fc80e1df98ba384a60f2a69843ac4)
