### ISSUE TITLE
joining game in progress causes out-of-sync (OOS)

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#20]
When a player joins a game in progress, after a minute or two, it causes an Out-of-sync problem, the player is disconnected. Other player may get disconnected as well.

**Comment by Jammyjamjamman** [comment]
There was a problem with saved games mentioned in issue #30. Joining games in progress will have been problematic because of this, (because it relies on saving, sending and loading the game,) so it would be worth testing if the bug is still present.

**Comment by andy5995** [comment]
tested locally, bug still present. thanks for taking care of #30 :)

**Comment by Jammyjamjamman** [comment]
Thanks for the info. I'll investigate OOS's more, but I think #26 is a more pressing OOS right now.

**Comment by andy5995** [comment]
I suspect that solving this might help solve #26 . Also.. this can be tested locally. With #26, you need to have a Windows and Linux player present to test.

**Comment by andy5995** [comment]
Oh, but that doesn't mean #26 shouldn't be prioritized. I meant this one might be easier to work on until we have more Windows testers.

**Comment by biels** [comment]
Does the game pause while sending and loading the save file? Maybe things happen in the game during this process and the initial save that the newly joined client gets is already offset by a little bit which ends up creating the OOS.

**Comment by andy5995** [comment]
Yes

**Comment by mathusummut** [comment]
[This commit makes OOS less of an issue.](https://github.com/ZetaGlest/zetaglest-source/commit/913ab85c35e5b2154e61468148905cf9dafeec75)

**Comment by mathusummut** [comment]
Closing the issue until this comes up again.
