### ISSUE TITLE
building should not get canceled if units gets in the way

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#203]
a worker should be able to build a building in a free area, even if there are units moving in that area. Related to that, building should not get cancelled if a unit suddenly moves into an area that has a building queued for that area.

**Comment by mathusummut** [comment]
[This is now solved.](https://github.com/ZetaGlest/zetaglest-source/commit/bbc97d02bb5f51b1f3642204a3d9f40db83cce10)
