### ISSUE TITLE
If player doesn't have enough cash, option to build a unit should be disabled 

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#205]
If player doesn't have enough cash, option to build a unit should be disabled

I either have to check my resources each time I want build something, or click and find out I don't have enough cash. It would be so much more user-friendly if the option to build something were just grayed out until the players has the resources to do.

**Comment by mathusummut** [comment]
[This is now fixed.](https://github.com/ZetaGlest/zetaglest-source/commit/c509fb1247e685f6e16d21c9a9d3ad4b7b7a3f40)
