### ISSUE TITLE
The tools should be removed

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#247]
Regarding the tools in 

https://github.com/ZetaGlest/zetaglest-source/tree/develop/source/tools

They're built when -DBUILD_MODEL_IMPORT_EXPORT_TOOLS=ON when passed to cmake. They are not installed when `make install` is run. The output binaries are `g2xml` and `xml2g`

The README in the [glexemel](https://github.com/ZetaGlest/zetaglest-source/tree/develop/source/tools/glexemel) directory states

```
=== GLEXEMEL ===
An XML format for the G3D file format used by the game Glest:
  http://www.glest.org

This XML format allows for exporters to create XML file descriptions that
can then be converted to binary.

Note: This package is not yet part of Glest, although it is offered for
inclusion should the developers wish.

Copyright (C) Jonathan Merritt 2005.
This package may be distributed under the terms of the GNU General Public
License (see the file COPYING for more details).
```

At some point the in the future, we could decide if these tools could be useful, whether or not they will be installed, and if so, add to the docs about them and mention them more prominently in the general documentation.

I have never used them and don't know what I'd use them for.

**Comment by mathusummut** [comment]
They can be removed. Their g3d spec is out of date anyways.

**Comment by andy5995** [comment]
As part of the removal patch, the cmake files will also need updating, as well as the build docs to indicate the option no longer exists.

**Comment by andy5995** [comment]
Completed in https://github.com/ZetaGlest/zetaglest-source/commit/aadf4c5e41e52669cad7c71c6e99fcf84049f181 and https://github.com/ZetaGlest/zetaglest-source/commit/c2dc7452996b0d21f4013e017d851615628900eb
