### ISSUE TITLE
icons need updating

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#250]
They can be redesigned, since ZetaGlest is a different game than MegaGlest. If anyone could create and submit samples, once approved, you can submit them with a PR.

https://github.com/ZetaGlest/zetaglest-source/tree/develop/mk/shared

![image](https://user-images.githubusercontent.com/16764864/46262661-da048500-c4c9-11e8-9f3f-ca884424fd47.png)

**Comment by andy5995** [comment]
We're keeping the same theme for now.. so any new icons should not clash with brown.

If you get icons from another source, the license should be public domain or Creative Commons Legal Code Attribution-ShareAlike 3.0 Unported and credits should be documented in https://github.com/ZetaGlest/zetaglest-data/blob/develop/docs/AUTHORS.data.txt

**Comment by jasperdanan** [comment]
Would like to work on this, I do some hobby graphics work.

**Comment by andy5995** [comment]
All yours then

**Comment by andy5995** [comment]
How's this coming along, @jasperdanan ?

**Comment by jasperdanan** [comment]
Still working on them! I had to finish some projects that popped up first, sorry about that @andy5995.
