### ISSUE TITLE
VLC-related code and files can be removed

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#257]
Using vlc for videos was something that was never fully implemented. The code and related files can be removed.

This output from `git grep` should provide some hints as to what files are affected:

https://gist.github.com/andy5995/52d91440ca078b05500871c384928fdf

**Comment by mukeshmk** [comment]
I want to work on this issue.

But before I can start, I have a question. I was just going through the code. I wanted to know the functionality of `video_player.h` and `video_player.cpp`, this would help me a little. They are being used in the code in a few places. And also are there any other video players apart from VLC?

Thanks in advance.

**Comment by andy5995** [comment]
Thank you for your interest @mukeshmk . I'll review the code some more and provide you with some specifics within a few days.

**Comment by mukeshmk** [comment]
Thanks, @andy5995 , I just wanted to know if you have any updates for me?

**Comment by andy5995** [comment]
No, not yet. @mathusummut is something you wanted done?

**Comment by mathusummut** [comment]
Let's leave the code in for now, just in case we ever want to include video playback into the game.
