### ISSUE TITLE
remove references to libxml

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#265]
libxml is no longer a dependency and references to it can be removed from this script

https://github.com/ZetaGlest/zetaglest-source/blob/develop/mk/linux/setupBuildDeps.sh

and also from packaging/debian/control

**Comment by Pranav1999** [comment]
I have created a pull request https://github.com/ZetaGlest/zetaglest-source/pull/269. All the checks have passed. Please review.
