### ISSUE TITLE
output library should be renamed

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#266]
The name of the library should just be "libzetaglest.a" not "liblib..."

```
[ 42%] Building CXX object source/shared_lib/CMakeFiles/libzetaglest.dir/sources/platform/unix/gl_wrap.cpp.o
[ 43%] Linking CXX static library liblibzetaglest.a
```

**Comment by mvilkin** [comment]
Seems like it will conflict with https://github.com/ZetaGlest/zetaglest-source/blob/develop/source/glest_game/CMakeLists.txt#L5

**Comment by mvilkin** [comment]
Yep, but you will have two targets with the same names.

**Comment by mathusummut** [comment]
My understanding is that GCC, CMake or some tool is automatically appending the "lib" prefix to the output. So if you have "libzetaglest", the output is called "liblibzetaglest", and if you have "zetaglest", the output is called "libzetaglest". So with the current configuration, the only way to have the library output named "libzetaglest" is to rename it to "zetaglest", which involves a conflict.

Am I correct @mvilkin?

**Comment by mvilkin** [comment]
Absolutely. Thx for excellent full explanation!

**Comment by andy5995** [comment]
@mathusummut that's a pretty fair assessment, but though things can sometimes appear automatic, there's almost always a way to override.

>Logical target names must be globally unique.

>Targets names created with add_executable, add_library, or add_custom_target are logical build target names. Logical target names must be globally unique because:

https://cmake.org/cmake/help/v3.7/policy/CMP0002.html?highlight=cmp0002

But this is how it's changed

[set_target_properties](https://cmake.org/cmake/help/v3.7/command/set_target_properties.html?highlight=set_target_properties)

>Targets can have properties that affect how they are built.

And this is the patch (but let's wait until after the build is fixed to merge it)

https://github.com/ZetaGlest/zetaglest-source/pull/277/files
