### ISSUE TITLE
Zoom out restriction should be removed during game

### ISSUE THREAD

**Issue by mathusummut** [ZetaGlest/zetaglest-source#27]
Not sure why it's there, really. A bit of zooming out would definitely be helpful. :)

**Comment by andy5995** [comment]
I notice there is no restriction when playing solo, not networked. I wonder if it zooming out too far would cause extra data to have to be sent. This is something I think @Jammyjamjamman might be able to answer.

**Comment by andy5995** [comment]
@mathusummut completed this in https://github.com/ZetaGlest/zetaglest-source/commit/b03ad32cddcade857f951d65f121ad16744b26e4 and https://github.com/ZetaGlest/zetaglest-source/commit/5f733a670726b4b84da78562755eade39d9aeb38
