### ISSUE TITLE
Max unit selection limit should be removed

### ISSUE THREAD

**Issue by mathusummut** [ZetaGlest/zetaglest-source#28]
It is incredibly frustrating and adds no benefit. The AI can control all units at once.

**Comment by andy5995** [comment]
ticket accepted and labelled

**Comment by Jammyjamjamman** [comment]
My suggestion for how to display what's selected: show an icon of the user, along with the number selected.

e.g. "<icon1> X 14, <icon2> X 33... etc"

**Comment by andy5995** [comment]
Yeah, that makes sense. If by "user", you mean "unit". xD

**Comment by mathusummut** [comment]
This is now [done](https://github.com/ZetaGlest/zetaglest-source/commit/fbe63bbacfae800fcecbdc7ed10c83dd5f0ea53d).
