### ISSUE TITLE
[discussion] Decide on a version number

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#3]
It will probably be months before the first release,
but does anyone have suggestions as to what the first version of the ZetaGlest fork should be?

0.01?

**Comment by dafky2000** [comment]
It would make sense to me to mirror the upstream version number and add an additional octet or extension. That way it's easy to track what has been merged and what features exist. Are you planning on keeping this up to date with upstream?

**Comment by biels** [comment]
We should take this into account since if we start refactoring things then it will be much harder to merge upstream changes. Do we want to add a layer on top of MG or diverge completely? In my opinion I'd go for the first.

**Comment by andy5995** [comment]
Well, I had assumed we wouldn't be merging with the upstream.

1. I already removed some code (#6)

2. The pace of patches on MG is painfully slow, and it seems that when people submit PR's, it takes a very long time to even get a comment on them.

3. MG wants feature requests filed on their forum. And if you spent time looking through them, you'll see a lot of good ideas that have been sitting there for a long time.
https://forum.megaglest.org/index.php?board=21.0

4. There are long-standing bugs that have no tickets filed for them, and clearly have not been worked on, and no indication of any time frame when or if they will get worked on.

5. I've been told my some players that adding more threading would help with the game slow-down when there are a lot of units on large maps. (I can't confirm that). I offered in the MG dev lobby if they had any chunks of code that needed threading, and got no response.

Now, I can't claim to know how to solve a lot of issues at this moment, but I am willing to accept pull requests, and hopefully grow the number of regular contributors over time, and plan to learn the code better myself.

@Jammyjamjamman @biels you have been with the MG project for a long time. Do you understand what I mean about some of what I listed above? And if so, do you agree that a complete divergence would be the best option?

>It would make sense to me to mirror the upstream version number and add an additional octet or extension. That way it's easy to track what has been merged and what features exist. Are you planning on keeping this up to date with upstream?

@dafky2000 , so the current release of MG is 3.13.0 . You are suggesting something like.. 3.13.1 or 3.13.z1 ?

**Comment by biels** [comment]
Well, after reading this I changed my mind about this. Yes I am familiar with many of these things. Posting on the MG forum offering help or making suggestions with low success rate being the first one. So yeah I agree with all of the claims. Regarding point 5, I think that the render thread is actually the same thread as the logic thread so if there are many units not only the fps go down but everything stalls. 
So yeah I guess diverging completely and using MG as a base to build a better thing is a better idea.

**Comment by dafky2000** [comment]
Definitely needs more discussion, if the upstream is behind that much it may not be worth following their versioning scheme at all. We wouldn't want to develop some bigger features and have to wait for 3.14.0 or v4.... Maybe I was a little off base...

After a little more research it seems like restarting at v1.0.0 **IS** common for this scenario. My only issue is easily tracking what version of upstream we are up to date with. One suggestion was to use semver build extensions/meta data (simply to stay compliant with semver), for example: 1.0.0-3.13.0. I like this, it is straight forward and decouples the 2 versions while still making it straight forward to devs and users what upstream features they can expect.

Some links:
https://softwareengineering.stackexchange.com/questions/31551/forked-a-project-where-do-my-version-numbers-start
https://github.com/semver/semver/issues/278
https://github.com/semver/semver/issues/264
https://github.com/semver/semver/issues/163#issuecomment-192662245

**Comment by andy5995** [comment]
>1.0.0-3.13.0. I like this, it is straight forward and decouples the 2 versions while still making it straight forward to devs and users what upstream features they can expect.

Thanks for researching that. I like that too, but it seems so long. To my thinking, using just 1.0.0 should be sufficient, and the docs can contain the info that states the version of MG from which ZG was forked.

But perhaps 1.0.01 would be good. Using the last 2 digits to represent smaller changes.

For the record, MegaGlest is a fork of [Glest](http://www.glest.org/en/index.php) (not that it matters for this discussion, but only a point worth noting).

But I'd like to see @Jammyjamjamman's opinion on this. He's a core player, as far back as the Glest days. He should be available... soon. And he's also quite knowledge about a wide variety of the inner workings of MG and other computery things.

**Comment by dafky2000** [comment]
Yea, typically you only show the extension version in a handful of places and you would only show the first three octets in most places anyways. If the project diverges from the upstream too much than this would likely become moot anyways as merging will become more and more difficult. Look forward to his reply :smile:

**Comment by andy5995** [comment]
I decided to go with 0.8.01. Because of the disconnects, and stacktrace messages that sometime show up,  going with 1.0 didn't feel quite right. @Jammyjamjamman's been busy with other things so I didn't ask him about it. I'm flexible to changing it before release though if there's a compelling reason to do so.
