### ISSUE TITLE
removing intro video

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#34]
The intro video can be removed. When ZG starts, it should go directly to the main menu.

This will get rid of the libvlc dependency. It's not causing any problems, but needs to be removed from the build as part of this change.

It would be great to remove all the code that would be unused after this change, and make things clean.

**Comment by adubenion** [comment]
Hi Andy,

I can take this one!

**Comment by andy5995** [comment]
Thanks @adubenion !

I was looking over the code more last night. It appears that the vlc dependency is used in other areas as well. When a user goes to the main menu, and after a battle. You should be able to find the other areas easily enough by doing different types of searches..

for example:

```
$ ack "vlc"
menu/menu_state_custom_game.cpp
4824:            string vlcPluginsPath =
4835:                                            true, vlcPluginsPath,

menu/menu_state_connected_game.cpp
8793:              vlcPluginsPath =
8805:                                            vlcPluginsPath,

menu/main_menu.cpp
195:          vlcPluginsPath =
207:                                               vlcPluginsPath,

main/battle_end.cpp
500:            vlcPluginsPath =
512:                                                 vlcPluginsPath,

main/intro.cpp
725:          vlcPluginsPath =
737:                                                vlcPluginsPath,

game/game.cpp
6447://		string vlcPluginsPath = Config::getInstance().getString("VideoPlayerPluginsPath","");
6455://							vlcPluginsPath,
6474:			string vlcPluginsPath = Config::getInstance().getString("VideoPlayerPluginsPath","");
6486:					vlcPluginsPath,
6502:				string vlcPluginsPath = Config::getInstance().getString("VideoPlayerPluginsPath","");
6514:						vlcPluginsPath,
```

And you're welcome to join our Discord chat server: https://discord.gg/WaAaXS7 to get any help along the way.

**Comment by andy5995** [comment]
How's this coming along @adubenion ? By the way, which operating system do you use? I assume if it's Windows then you are waiting for us to complete the Windows build instructions so you'd be able to actually test your work. xD

**Comment by adubenion** [comment]
Hahaha, sounds just about right. I'm definitely running on a windows machine! xD I'm also not the best with c++, but I'm chugging along... Could require some eyes at some point to make sure I'm not wildly going in the wrong direction.

My apologies for the late response, I've been a little under the weather as of recent.

**Comment by andy5995** [comment]
No problem, and thanks for working on this.

Happy give a second pair of eyes. I think we're all learning, :).

While you're in the source dir, you can use `git diff`. You can redirect the output to a text file

`git diff > patch_34.txt`, then open the file with text editor. Copy and paste it to https://gist.github.com/

Click on "create secret gist" and then paste the link here.

**Comment by andy5995** [comment]
Since no work has been done on this yet, I'm going to close this ticket and try to get https://github.com/ZetaGlest/zetaglest-data/pull/56 merged in after review.

It may not be worth it in the long run to maintain the code that plays menu animations, but right now it's very low priority.
