### ISSUE TITLE
updating Windows build process

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#37]
We're working on updating the Windows build script, to make it easier than ever to build on Windows. xD And also to make sure ZG can be compiled on Windows with updated dependencies.

There's been some discussion in the Discord chat room, but I'm creating a ticket so progress can be tracked more easily (hopefully).

**Comment by mathusummut** [comment]
Today I configured the MinGW compiler, tomorrow I will attempt to fix dependencies and compile ZG.

**Comment by andy5995** [comment]
@Jammyjamjamman mentioned something about Network Throttling in Windows.

Do you suppose that this registry entry is supposed to be imported into a user's registry to prevent OOS on Windows? Or that's it's imported automatically when installing a release?

https://github.com/ZetaGlest/zetaglest-source/blob/develop/mk/windows/NetworkThrottleFix.reg

**Comment by mathusummut** [comment]
At the installation, the user should be presented with a checkbox called "Network Optimization", which should be checked by default. If the user clicks "Finish" and the checkbox is checked, then merge the reg file.

**Comment by Jammyjamjamman** [comment]
I think net throttling happens in megaglest too and this is probably not the reason for the OOS's, IMO.

**Comment by mathusummut** [comment]
I still think it should be added as an option, because it may affect people who are playing over wifi while streaming for example.

**Comment by Jammyjamjamman** [comment]
Is it normal for programs to fiddle with the registry? This sounds like something windows and antiviruses would get very upset about to me xD.

**Comment by mathusummut** [comment]
It is the most normal thing you can imagine.

**Comment by Jammyjamjamman** [comment]
I guess I'd be alright with this then xD

**Comment by andy5995** [comment]
I'll defer to @mathusummut judgement on this. But if any other Windows users or devs want to chime in, some extra feedback couldn't hurt.

**Comment by andy5995** [comment]
>Do you suppose that this registry entry is supposed to be imported into a user's registry to prevent OOS on Windows?

Now we know that isn't the cause of the Windows/Linux OOS.

Also, if the case is that the registry entry is imported at the time of installation, then David would have already had it from installing the last version of MG.

**Comment by andy5995** [comment]
@mathusummut Can you give us a status report?

**Comment by mathusummut** [comment]
Only 75 linker errors to go (which is a lot less than before)! :D

**Comment by andy5995** [comment]
In the short-term, is there any reason why I couldn't create a repo for the existing deps, then they could be updated one-at-a-time?

We could change [build-mg-2015.bat](https://github.com/ZetaGlest/zetaglest-source/blob/develop/mk/windows/build-mg-2015.bat) to retrieve them from the new repo. And edit the script so instead of getting a single huge archive, it would retrieve each dependency individually.

Would that be a good short-term solution?

**Comment by mathusummut** [comment]
Unfortunately the `/mk/windows` folder has been almost completely changed and re-organised in my local repo, so let's leave it pulling from softcoder from now. I am still trying to solve linker errors from the new dependencies on my end.

**Comment by andy5995** [comment]
@mathusummut provided all the new stuff in https://github.com/ZetaGlest/zetaglest-source/pull/92

The files were 6G and so I separated it into various repos, and linked to each using submodules.

See https://github.com/ZetaGlest/zetaglest-source/tree/develop/mk to get an overview of the structure

Most people will not want to clone the zg-source repo recursively; that would download the data from the submodules, which they'll never need.

Now all that's needed are docs for working with those submodules.

**Comment by andy5995** [comment]
Read-only access, for people who only want to download the latest source to build, not necessarily contribute or make changes

the ZG source repo is cloned as normal.

While in the top-level dir of the source directory...

Clone the windows64 repo:

`git submodule update --init mk/windows64`

Because win64-vs2015 is a submodule of windows64, one must be in the windows64 directory before cloning win64-vs2015:

To clone the win64-vs2015 repo:

`cd mk/windows64`
`git submodule update --init vs2015`

**Comment by andy5995** [comment]
This is what needs to happen after a file is updated in a windows repo.

After the windows64 repo is updated, the link to it in zetaglest-source needs to be updated. Otherwise, a user checking for updates will not receive them. That's because the link to the submodule points to a specific commit on windows64. That "commit link" must be updated (those links can be viewed by browsing the repo online).

`cd mk/windows64`
`git pull`
`cd ..`

Then commit the change and push (or PR) to the ZG source repo. Only 2 files will have changed.

And following the same instructions above, after a win-vs???? repo is updated, the link to it in windows64 must be updated.

From the windows64 repo

`cd vs2015`
`git pull`
`cd ..`

commit and push (or PR) the change.

**Comment by mathusummut** [comment]
I am happy to report that now everything builds and works properly. :)
