### ISSUE TITLE
removing the mod center

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#39]
Is the mod center a needed feature?

Are there a lot of gamers that don't know how to download an extract a compressed file into a specific directory?

The mod center would be more helpful if mods could also get updated. I think that might be a feature that was being worked on. I see these two options in glest.ini

https://github.com/ZetaGlest/zetaglest-source/blob/70ec6b4269c7d7ea32b3120fb37047d8e44155fe/mk/linux/glest.ini#L11-L12

So to my thinking.. if data and mods could get auto-updated, that would make it much more convenient for users to install mods.

However.. it's a lot of extra code to maintain. It would be nice if we could focus on the GAME to keep making it GREATER.

We do want to make mods visible, and provide direct links to them! And have a system in place where users can see NEW mods, and see when older mods are UPDATED!

This this end, I've started experimenting adding them as submodules to the data repo:

ZetaGlest/zetaglest-data#30

https://github.com/ZetaGlest/zetaglest-data/commit/b9f9183bf6cb31d59f8f7637e5742b6bca7d9bab

**Comment by mathusummut** [comment]
I think the mod centre is an excellent feature and should not be removed. Its purpose is to present a list of most available third-party scenarios, and to download them automatically. It's a nice package manager to have imo.

**Comment by andy5995** [comment]
The opinion of a senior modder holds a lot of weight here.
