### ISSUE TITLE
Dependencies for Linux in BUILD.MD not up to date

### ISSUE THREAD

**Issue by Unnoog** [ZetaGlest/zetaglest-source#61]
It seems that the dependencies for Linux in BUILD.MD are not up to date anymore.

The following libraries are needed to compile : 
g++
liblua5.2-dev
libcurl4-gnutls-dev

If it's OK with you guys, I'd like to update it and make my first ever contribution to an open source project!

Final list would be : 

gcc g++ cmake libsdl2-dev libalut-dev libgl1-mesa-dev libglu1-mesa-dev libvorbis-dev libx11-dev liblua5.2-dev libjpeg-dev libpng-dev libcurl4-gnutls-dev libircclient-dev libglew-dev libftgl-dev libfribidi-dev libcppunit-dev libminiupnpc-dev libfreetype6-dev libgnutls28-dev libkrb5-dev libkrb5-dev libnghttp2-dev libopenal-dev libldap2-dev libwxgtk3.0-dev librtmp-dev libvlccore-dev libvlc-dev

Tested with a brand new install of Ubuntu (ie: compilation + played tutorials)

**Comment by andy5995** [comment]
Wow, thank you for the offer @Unnoog ! That would be great!

>Tested with a brand new install of Ubuntu (ie: compilation + played tutorials)

We'll play a co-op game sometime, just give me a ping if you ever see me in the lobby. Don't worry about your skill level; we'll just adjust the AI accordingly to try to make a challenging but winnable game. :)
