### ISSUE TITLE
When the default action should be move instead of attack

### ISSUE THREAD

**Issue by mathusummut** [ZetaGlest/zetaglest-source#62]
Default command should be move instead of attack if any of the following conditions are met:

-  If the player selects a unit from a faction of their team as the target location, where a move command should be sent in that case

- If any of the units in the selection are in attack-mode already. In a battle situation, I would like to be able to use right-click to pull the units away from the battle scene. To do this, we can make right-click send move if at least one unit in the selection is attacking.

**Comment by andy5995** [comment]
>If any of the units in the selection are in attack-mode already.

I was trying to implement this code yesterday. It didn't work, and I've gotta take  a break from it, but I'll definitely keep it in mind, as well as the first suggestion you listed.

**Comment by mathusummut** [comment]
[Now double right-clicking sends a move [command](https://github.com/ZetaGlest/zetaglest-source/commit/b40fc2a011843ec17fed0dd1414a52326dcb9cf1) which resolves this issue.
