### ISSUE TITLE
Production resets when cancelling item in production queue.

### ISSUE THREAD

**Issue by Jammyjamjamman** [ZetaGlest/zetaglest-source#67]
if you create a queue of, say, 7 archers and then a stickman in the bigtent, then you cancel the stickman (the last item added to the queue), the progress of the current unit being produced is reset. The progress of the current production should continue unperturbed.

It's possible I created this bug when I fixed  #30.

The commit is https://github.com/ZetaGlest/zetaglest-source/commit/d96a63796ee4f43641c7811701828786e22acf56

**Comment by andy5995** [comment]
@Jammyjamjamman can this be closed?

**Comment by Jammyjamjamman** [comment]
@andy5995 sorry for not responding earlier. Yes I believe it was, so I'm closing this issue.

**Comment by andy5995** [comment]
np, Jammy. If I needed to know sooner, I would have just pinged you again.
