### ISSUE TITLE
installer script needs updating

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#71]
I did some work on this last week.

https://github.com/ZetaGlest/zetaglest-source/blob/develop/mk/linux/tools-for-standalone-client/installer/make.sh

I didn't finish it though. It seems to call scripts from https://github.com/ZetaGlest/zetaglest-source/tree/develop/mk/linux to create a binary and data archive.

Some of the variables it uses should be in a single file, such as the data dir repo.

Also, it could use some error checking. I've seen it give a "completed successfully" message when it didn't really complete successfully.

I'm sure it worked fine before we changed the name of the program to ZetaGlest and moved the data dir, but it would be nice if the scripts were updated to make changes easier in the future. Maybe some fan of the game will want to fork it someday! xD

For that script to work, the [mojosetup fork](https://github.com/ZetaGlest/mojosetup-fork) must be cloned into the [installer/mojosetup](https://github.com/ZetaGlest/zetaglest-source/tree/develop/mk/linux/tools-for-standalone-client/installer) directory. And also cloning the [data dir](https://github.com/ZetaGlest/zetaglest-data) is needed. The data dir needs to be adjacent to the source dir:

For example:

    ZetaGlest/zetaglest-source
    ZetaGlest/zetaglest-data

**Comment by Jammyjamjamman** [comment]
Out of interest, what is your opinion on continuing with an installer?
Because a lot of major programs just provide some compressed archive (e.g. blender, supertuxkart, teamviewer etc.).
I guess we would still need a way to "pack" everything, so it's probably easier sticking to the current system. Your idea sounds good to me.

**Comment by andy5995** [comment]
Oh, I guess I wasn't clear in my post above. So the "make.sh" script creates an installer which has the data and source included.

It calls some separate scripts that are designed to create a separate data archive, and separate source archive.

I'm fine with continuing with an installer. I think we could also offer a separate "source-only" archive like MG does, with a separate "data-only" archive.

**Comment by biels** [comment]
@Jammyjamjamman I think having an installer is a very good thing. It makes it easier to install, so it helps in user experience. I think that everything that helps in UX is nice to have. Especially if we already have it.

**Comment by mathusummut** [comment]
On Windows this is now ready. Should it also be done on Linux?
