### ISSUE TITLE
Unit selection issue

### ISSUE THREAD

**Issue by mathusummut** [ZetaGlest/zetaglest-source#74]
When selecting multiple units, if a building is accidentally included in the selection, the selected building causes the units to be deselected, which is incredibly counterproductive.

**Comment by Jammyjamjamman** [comment]
I think @andy5995 suggested this has something to do with adding "multiselect" tag in workers XML. I assume what Andy did, was activate the tag and specified that you can only multiselect the same unit.

By default, the colourpicker will select moving units over buildings.  (I think, or it selects units under other units). Using the multiselect tag probably bypasses this preferential selection.

**Comment by andy5995** [comment]
Actually it's the uniform-selection that causes the side-effect. When combined with multi-select=true.

https://github.com/ZetaGlest/zetaglest-data/commit/ac7d2af266cbdb555331bb271f1fe8069613176d

What faction were you playing, @mathusummut ? I didn't change it for all factions yet.

I started making that change to help solve an issue @biels mentioned in #8 

>Units that can attack go attacking and units that can't go moving. If you had a building selected for some reason as well it simply wouldn't do anything. That would apply only when you make right click on the floor.

When "uniform-selection=true", that means you can't have different units as part of the selection group. Which means you can't have workers mixed with archers (which would disable the attack command) and you can't have workers mixed with buildings (which would disable the move command).

But as you and Jammy noted, there is a side effect; workers become un-selected very easily.

Therefore, I believe that fixing the issue @biels mentioned  may require source code changes, not xml changes.

To temporarily work-around the problem of units being unselected, the uniform-selection=true can be changed to "false".

**Comment by mathusummut** [comment]
My brother told me this happened to him while playing Elves.

**Comment by andy5995** [comment]
Ok, and that was one of the factions I changed. Greece was the other one. Actually since it was just one unit, I may have done that to all the factions. I'll make a ticket to reverse it in data.

**Comment by mathusummut** [comment]
In the XML, I think we should add another tag: <building>true</building>, and modify the source code to separate selections for units with building set to "true" from those with building set to "false".

**Comment by andy5995** [comment]
This can be closed when https://github.com/ZetaGlest/zetaglest-data/issues/54 is completed.

**Comment by andy5995** [comment]
>In the XML, I think we should add another tag: <building>true</building>, and modify the source code to separate selections for units with building set to "true" from those with building set to "false".

I think this can be done w/o adding an extra tag, by checking to see if a unit has the "move" skill

**Comment by mathusummut** [comment]
This is fixed now, as [this is completed](https://github.com/ZetaGlest/zetaglest-data/issues/54).
