### ISSUE TITLE
attack icon should be the same for all factions, and indicate "Attack" more clearly

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#76]
I think the attack icon should be the same for all factions.

This is the icon an Indian stickfighter has for attack.

![screenshot_2018-02-25_10-21-05](https://user-images.githubusercontent.com/16764864/36643746-9edf978a-1a15-11e8-8e56-0af3e36fb827.png)

I think it would be better, esp for new users, if the attack icon more clearly indicated that it's an attack icon; also, I don't really see any reason why the attack icon couldn't be the same for all combat units in all factions. A standard basically, so when clicking a combat unit, one can easily see which icon is used for attack.

**Comment by mathusummut** [comment]
I think the stop, cancel, move and attack icons should be the same for units within a faction, but it should be different for each faction to fit the styling of the particular faction better.

**Comment by andy5995** [comment]
Ok.. we'll go with that, along with #75.
