### ISSUE TITLE
Default command on right click (move / attack)

### ISSUE THREAD

**Issue by biels** [ZetaGlest/zetaglest-source#8]
I would give priority to the attack command over the move command on units that have it, so that when you right click on the floor, a unit that can attack walks there with the attack command. Also, if the unit is in a group together with units that can't attack, different orders should be given to different units. Units that can attack go attacking and units that can't go moving. If you had a building selected for some reason as well it simply wouldn't do anything. That would apply only when you make right click on the floor.
Sure sometimes it is useful to actually move the unit with the move command for example to position units in a battle or to retreat. But you can already do it with the M key (although I would change that mechanic of interacting with menus as proposed in #7 for producing units).

Implementation wise (what I can think of) would be the following:
selectedUnits.forEach(unit -> unit.defaultHeadCommand(targetLocation))
And unit.defaultHeadCommand(Location targetLocation) would do nothing for units that can't move, move units that can only move and head attacking for units that have an attack skill. (Here I'm using head as a synonym for going to somewhere since move already means "move without attacking")

**Comment by andy5995** [comment]
I think I know what you mean. If I have a bunch of warrior units inside the selection box, but there is a worker accidentally mixed in with them, the attack command doesn't work at all. In fact, no attack command shows because the single worker doesn't have that "skill".

Many new players wouldn't think to check for a worker, and experienced players would have to find the worker and get him out of the selection unit.

A problem esp. if you're in an emergency combat situation at the time.

**Comment by andy5995** [comment]
>I would give priority to the attack command over the move command on units that have it, so that when you right click on the floor, a unit that can attack walks there with the attack command.

Oh! I misunderstood you @biels . On first thought, I agree with you. We should ask @Jammyjamjamman about it. It seems to me the attack command is used more often than the move command. And in battle, it would allow for less keystrokes.

>Also, if the unit is in a group together with units that can't attack, different orders should be given to different units. Units that can attack go attacking and units that can't go moving.

Part of solving this problem would be adding this to the worker xml files

<uniform-selection value="true"/>

If that's set on unit, only that unit can be selected. So you wouldn't be able to add workers to a group of archers, for instance.

**Comment by andy5995** [comment]
>I would give priority to the attack command over the move command on units that have it, so that when you right click on the floor, a unit that can attack walks there with the attack command.

That's done.

>Also, if the unit is in a group together with units that can't attack, different orders should be given to different units. Units that can attack go attacking and units that can't go moving. If you had a building selected for some reason as well it simply wouldn't do anything. That would apply only when you make right click on the floor.

A separate ticket is needed for that.

**Comment by mathusummut** [comment]
@andy5995 the selection mechanism already works like that in the newest version, so there's no need for a ticket! :D

**Comment by andy5995** [comment]
>Also, if the unit is in a group together with units that can't attack, different orders should be given to different units. Units that can attack go attacking and units that can't go moving. If you had a building selected for some reason as well it simply wouldn't do anything. That would apply only when you make right click on the floor.

>A separate ticket is needed for that.

@mathusummut , he's referring to #156 I think (I just created a separate ticket).
