### ISSUE TITLE
change how "attack" and "move" work

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#80]
Related ticket (#62)

Discord notes:

mathusummut - Last Saturday at 4:39 PM
Please remove the 'A' and 'M' keyboard shortcuts. Right-click should be used exclusively instead.
February 25, 2018

Biel - Last Sunday at 8:37 AM
But how do you choose the action then? I agree with you that having to press the key is not a great user experience

Jammy - Last Sunday at 8:47 AM
'a' key can be used for units which can attack but are not attacking type units(edited)
also 'm' is needed for retreating units

mathusummut - Last Sunday at 9:14 AM
@Biel you can use the mouse
@Jammy I already issued a ticket for that. If at least one unit in the selection is in attack mode (ie. currently attacking), then the command issued with right-click should be move

Biel - Last Sunday at 9:21 AM
So more like a toggle
Jammy - Last Sunday at 9:22 AM
hm... this is complicated

Biel - Last Sunday at 9:22 AM
Then orders are no longer "idempotent"
mathusummut - Last Sunday at 9:22 AM
complicated to implement, sure, but it's what the user expects

Jammy - Last Sunday at 9:23 AM
commands are issued independently, on separate threads, so what happens if you select a mixture of attacking and and stopped units, what happens?
mathusummut - Last Sunday at 9:23 AM
oh, on separate threads?

Biel - Last Sunday at 9:24 AM
We should create a concept of issuing commands to a selection of units
Instead of just looping over the selection and executing commands

Jammy - Last Sunday at 9:24 AM
....... that's exactly what doesn't happen
but if you select a mixture of attacking and stopped units, IMO you would have to somehow first check: "are any of the units  not attacking?"(edited)
if yes, make them all attack

mathusummut - Last Sunday at 9:26 AM
@Biel to send another move command to the selected units (which were attacking, then were moved with right click), the user would have to double right-click if an enemy is in sight and the user wants to pull units from the scene lmao

Jammy - Last Sunday at 9:27 AM
LOL discord needs to implement proper markdown
mathusummut - Last Sunday at 9:28 AM
In attack, because one right-click would be move, the second one would be attack (as no unit in the selection is attacking any longer), so subsequent moves would require double right-click

andy5995 - Last Sunday at 9:37 AM
I already issued a ticket for that. If at least one unit in the selection is in attack mode (ie. currently attacking), then the command issued with right-click should be move
 @mathusummut that should probably be in a separate ticket, so it can be found more easily
https://github.com/ZetaGlest/zetaglest-source/issues/62
GitHub
When the default action should be move instead of attack · Issue #62 · ZetaGlest/zetaglest-source
Default command should be move instead of attack if any of the following conditions are met:

If the player selects a unit from a faction of their team as the target location, where a move command...

It was a added as a 2nd bullet point.
Definitely we need to decide on how how move/attack works. The biggest problem to in MegaGlest that most new users didn't know to use the "A" key. I was told to use the A key by titi, and I have had to tell other players to use the A key.
Now there are clearly some new challenges with the default being attack.
Besides what you all have talked about here, we could advise users by adding some helpful hints in one, or all, of the tutorials.
But yes, of course, we can also change how move and attack works
I don't see eliminating corresponding keyboard options for attack and move in favor of exclusively using the mouse. though as in MG , M was not needed because A simple right click would move, and no M key had ever been defined.  So by that logic, the A key would not be needed now, if the default right click is attack.

mathusummut - Last Sunday at 9:54 AM
Ok, maybe they shouldn't be removed, but we should not rely on them.
imo of course

Jammy - Last Sunday at 9:55 AM
I would be very happy to see a more intelligent mouse control, I just don't know how to do it XD(edited)

mathusummut - Last Sunday at 9:56 AM
I'll try to work on this after I build

Jammy - Last Sunday at 9:56 AM
awesome!
I'd feel better about it if I work out howtopointer
or references

andy5995 - Last Sunday at 10:05 AM
One thing that may help us decide is looking at how other RTS games do this. This for example, is a full list of 0 A.D. hotkeys https://trac.wildfiregames.com/wiki/HotKeys

**Comment by andy5995** [comment]
related:
 
right click no longer attacks teammates https://github.com/ZetaGlest/zetaglest-source/commit/1d2543fb6a9d76f33d581b56bd30587dff0d8c06

**Comment by mathusummut** [comment]
[Double right-clicking sends a move command instead of an attack [command](https://github.com/ZetaGlest/zetaglest-source/commit/b40fc2a011843ec17fed0dd1414a52326dcb9cf1) which resolves this issue.

**Comment by biels** [comment]
On my installation (v0.8.01-dev) the double right click to move is not working
