### ISSUE TITLE
link to units from external factions

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#85]
When making custom techtrees, right now, there's a way to use "faction" links so the data for that faction doesn't need to be included. It will use the data from an external tech tree.

For instance, in the egypt unit folder of a custom mod, there only needs to be a single file, egypt.xml, with this content:

```
<?xml version="1.0" standalone="no"?>

<link>
    <techtree name="megapack"/>
</link>```

@mathusummut suggested that a similar feature be implemented for individual units.

The idea of using symbolic links were mentioned.

I'm not sure yet if symlinks are the way to go; but definitely the feature to link to units should be implemented.

Can anyone anticipate a problem with using symlinks? And do GitHub repos support symlinks?

**Comment by andy5995** [comment]
@mathusummut is working on this. I think @KeithSammut is too.

**Comment by KeithSammut** [comment]
oh, actually mathu is, I just need it.

**Comment by mathusummut** [comment]
[This feature is now added.](https://github.com/ZetaGlest/zetaglest-source/commit/e6d37f37fb5a2b48241bc57cb12036c331cbdc9a)
