### ISSUE TITLE
appearance of nicks in lobby list

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#98]
I like what our new friend @alketii did here:

https://github.com/ZetaGlest/zetaglest-source/commit/045b0b88e051f7163fbef42fa0adc63a326ca186

I disliked using ZG_ to prefix usernames but hadn't thought of a better method.

I think there needs to be a way to distinguish people logged in through regular IRC, and those logged in through the ZG client.

We could have a '*' next to people who are logged in through a ZG client. And then in the master server announcement (not yet created), a statement noting that only players with '*' next to their name are available for playing

I'm open to other ideas as well.

**Comment by alketii** [comment]
They are already distinguished by the ZG_ and _nnn, its just that buttons don't display those, but only the nickname. In IRC you could see it, but not on ZG lobby.

**Comment by andy5995** [comment]
I mean how they appear in the ZG client.  Have you ever noticed that when you're at the lobby, you can only click on ZG users, but not those logged in through IRC?

The MG announcement states to click on a user name...

But if I click on an IRC name, nothing happens.

If I click on the name of someone who is logged in with ZG, then their name appears in the chat console, and then I can hit enter; at which point the chat message is sent, and the user gets an audible ping.

That's not really a problem for people familiar with the game, but do you see how it could be confusing to new users? In fact, new users don't even know about the user name pinging thing. I remember when I first  played with you and the MG gang, I would hear whistles but I didn't know to check the chat console at the bottom of the screen. And I was too focused on the game so I didn't notice new messages at the bottom right away. Now I know to look there.

Ok, but trying it now, I see that clickable names are at least indicated by some highlighting on the button. But I think there needs to be just a little bit of something else to make it clearer to new players.

Now that I've explained my reasoning more, anyone else agree?

**Comment by alketii** [comment]
Yes I agree,
we can make the buttons of people from IRC clickable but with an "away" icon or something.
What do you suggest ?

**Comment by andy5995** [comment]
No ideas from me yet.
